version: "2"
services:
  backend:
    build: .
    ports:
      - "8080:3000"
    environment:
      - MONGO_URL=mongodb://db:27017/deployments
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
